config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    sessions: 'users/sessions'
  }
  root 'static#dashboard'
  get 'category/business'
  get 'category/entertainment'
  get 'category/studentorg'
  get 'category/social'
  get 'category/fundraising'
  get 'category/sport'
  get 'category/music'
  get 'category/educational'
  get 'category/townhall'
  get 'category/promotional'
  get 'category/allevents'
  get 'static/dashboard'
  get 'static/manager'
  get 'static/footer'
  get 'static/superuser'
  get 'static/contactus'
  get 'static/header'
  get 'static/eventdetails'
  get 'static/admindashboard'
  get 'static/home'
  get 'static/signin'
  resources :ads
  resources :users
  resources :events do 
    member do 
      put "like" =>"events#upvote"
      put "unlike"=>"events#downvote"
    end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/ad.rb
class Ad < ApplicationRecord
    enum status: [:archived, :published, :draft, :pending_review, :removed]
end

app/controllers/ads_controller.rb
class AdsController < ApplicationController
  before_action :set_ad, only: [:show, :edit, :update, :destroy]

  # GET /ads
  # GET /ads.json
  def index
    @ads = Ad.all
  end

  # GET /ads/1
  # GET /ads/1.json
  def show
  end

  # GET /ads/new
  def new
    @ad = Ad.new
  end

  # GET /ads/1/edit
  def edit
  end

  # POST /ads
  # POST /ads.json
  def create
    @ad = Ad.new(ad_params)

    respond_to do |format|
      if @ad.save
        format.html { redirect_to @ad, notice: 'Ad was successfully created.' }
        format.json { render :show, status: :created, location: @ad }
      else
        format.html { render :new }
        format.json { render json: @ad.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /ads/1
  # PATCH/PUT /ads/1.json
  def update
    respond_to do |format|
      if @ad.update(ad_params)
        format.html { redirect_to @ad, notice: 'Ad was successfully updated.' }
        format.json { render :show, status: :ok, location: @ad }
      else
        format.html { render :edit }
        format.json { render json: @ad.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /ads/1
  # DELETE /ads/1.json
  def destroy
    @ad.destroy
    respond_to do |format|
      format.html { redirect_to ads_url, notice: 'Ad was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_ad
      @ad = Ad.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def ad_params
      params.require(:ad).permit(:title, :details, :date_posted, :imgurl, :price, :upvotes, :downvotes)
    end
end

app/helpers/ads_helper.rb
module AdsHelper
end

app/views/ads/_form.html.erb
<%= form_with(model: ad, local: true) do |form| %>
  <% if ad.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(ad.errors.count, "error") %> prohibited this ad from being saved:</h2>

      <ul>
      <% ad.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title, class: 'form-control' %>
  </div>

  <div class="field">
    <%= form.label :details %>
    <%= form.text_area :details, class: 'form-control' %>
  </div>

  <div class="field">
    <%= form.label :date_posted %>
    <%= form.datetime_select :date_posted, class: 'form-control' %>
  </div>

  <div class="field">
    <%= form.label :imgurl %>
    <%= form.text_field :imgurl, class: 'form-control' %>
  </div>

  <div class="field">
    <%= form.label :price %>
    <%= form.text_field :price, class: 'form-control' %>
  </div>

  <div class="field">
    <%= form.label :upvotes %>
    <%= form.text_field :upvotes, class: 'form-control' %>
  </div>

  <div class="field">
    <%= form.label :downvotes %>
    <%= form.text_field :downvotes, class: 'form-control' %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/ads/edit.html.erb
<h1>Editing Ad</h1>

<%= render 'form', ad: @ad %>

<%= link_to 'Show', @ad %> |
<%= link_to 'Back', ads_path %>

app/views/ads/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Ads</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Details</th>
      <th>Date posted</th>
      <th>Imgurl</th>
      <th>Price</th>
      <th>Upvotes</th>
      <th>Downvotes</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @ads.each do |ad| %>
      <tr>
        <td><%= ad.title %></td>
        <td><%= ad.details %></td>
        <td><%= ad.date_posted %></td>
        <td><%= ad.imgurl %></td>
        <td><%= ad.price %></td>
        <td><%= ad.upvotes %></td>
        <td><%= ad.downvotes %></td>
        <td><%= link_to 'Show', ad %></td>
        <td><%= link_to 'Edit', edit_ad_path(ad) %></td>
        <td><%= link_to 'Destroy', ad, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Ad', new_ad_path %>

app/views/ads/new.html.erb
<h1>New Ad</h1>

<%= render 'form', ad: @ad %>

<%= link_to 'Back', ads_path %>

app/views/ads/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @ad.title %>
</p>

<p>
  <strong>Details:</strong>
  <%= @ad.details %>
</p>

<p>
  <strong>Date posted:</strong>
  <%= @ad.date_posted %>
</p>

<p>
  <strong>Imgurl:</strong>
  <%= @ad.imgurl %>
</p>

<p>
  <strong>Price:</strong>
  <%= @ad.price %>
</p>

<p>
  <strong>Upvotes:</strong>
  <%= @ad.upvotes %>
</p>

<p>
  <strong>Downvotes:</strong>
  <%= @ad.downvotes %>
</p>

<%= link_to 'Edit', edit_ad_path(@ad) %> |
<%= link_to 'Back', ads_path %>