config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    sessions: 'users/sessions'
  }
  root 'static#dashboard'
  get 'category/business'
  get 'category/entertainment'
  get 'category/studentorg'
  get 'category/social'
  get 'category/fundraising'
  get 'category/sport'
  get 'category/music'
  get 'category/educational'
  get 'category/townhall'
  get 'category/promotional'
  get 'category/allevents'
  get 'static/dashboard'
  get 'static/manager'
  get 'static/footer'
  get 'static/superuser'
  get 'static/contactus'
  get 'static/header'
  get 'static/eventdetails'
  get 'static/admindashboard'
  get 'static/home'
  get 'static/signin'
  resources :ads
  resources :users
  resources :events do 
    member do 
      put "like" =>"events#upvote"
      put "unlike"=>"events#downvote"
    end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/event.rb
class Event < ApplicationRecord
    acts_as_votable
    enum status: [:archived, :published, :draft, :pending_review, :removed]
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: [:show, :edit, :update, :destroy]

  # Upvote and Downvote Functionality
  def upvote 
    @event = Event.find(params[:id])
    @event.upvote_from current_user
    redirect_back(fallback_location: events_path)  
  end
  
  def downvote 
    @event = Event.find(params[:id])
    @event.downvote_from current_user
    redirect_back(fallback_location: events_path)  
  end
  
  # GET /events
  # GET /events.json
  def index
    params.permit(:category_name)
    @category_name = params[:category_name]
    
    if params[:category_name]
      @events = Event.where("category like ?", @category_name)
    else
      @events = Event.all
    end
    
  end

  # GET /events/1
  # GET /events/1.json
  def show
  end

  # GET /events/new
  def new
    @event = Event.new
  end

  # GET /events/1/edit
  def edit
  end

  # POST /events
  # POST /events.json
  def create
    @event = Event.new(event_params)

    respond_to do |format|
      if @event.save
        format.html { redirect_to @event, notice: 'Event was successfully created.' }
        format.json { render :show, status: :created, location: @event }
      else
        format.html { render :new }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /events/1
  # PATCH/PUT /events/1.json
  def update
    respond_to do |format|
      if @event.update(event_params)
        format.html { redirect_to @event, notice: 'Event was successfully updated.' }
        format.json { render :show, status: :ok, location: @event }
      else
        format.html { render :edit }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1
  # DELETE /events/1.json
  def destroy
    @event.destroy
    respond_to do |format|
      format.html { redirect_to events_url, notice: 'Event was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_event
      @event = Event.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def event_params
      params.require(:event).permit(:cost, :name, :time, :category, :date, :title, :description, :details, :location, :imgurl, :tags, :org, :upvotes, :downvotes, :extlink)
    end
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/_eventshow.html.erb
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="../images/CougPostingsLogo.png">

    <title>Coog Postings Dashboard</title>
      
            <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.7/js/bootstrap.min.js"></script>
      
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
      
    <!-- Bootstrap core CSS -->
    <link href="../../dist/css/bootstrap.min.css" rel="stylesheet">
    
      <!-- Font Awesome -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
  <!-- Bootstrap core CSS -->
  <link href="css/bootstrap.min.css" rel="stylesheet">
  <!-- Material Design Bootstrap -->
  <link href="css/mdb.min.css" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="" rel="stylesheet">
  </head>

<body>

<main role="main">

<br>
<br>
<div class="container-fluid" style="padding-left:100px; padding-right:100px;">
  <div class="row">
    <div class="col-md-12">
      <h1 align="center"><%= @category_name %> Events</h1>
    </div>
    <% if @events.empty? %>
      <p class="display-4 mx-auto">No events to show!</p>
    <% else %>
    <% @events.each do |event| %>

                        
<div class="col-sm-6 col-md-4 col-lg-3 col-xl-3 pt-4 pb-4">
 <!-- Card -->
<div class="card">
  <!-- Card image -->
   <% @reroute = "/events/" + event.id.to_s %>
    <a href="<%= @reroute %>">
  <div class="view overlay">
    <img class="card-img-top" src="<%= event.imgurl %>" style="height:200px">
    <a>
      <div class="mask rgba-white-slight"></div>
    </a>
  </div></a>


  <!-- Card content -->
  <div class="card-body">

    <!-- Title -->
    <h4 class="card-title"><%= event.name %></h4>
    <hr>
    <!-- Text -->
    <p class="card-text text-muted"> Location: <%= event.location %></p>
    <p class="card-text">Description</p>

  </div>

  <!-- Card footer -->
  <div class="rounded-bottom mdb-color lighten-3 text-center pt-3" style="background-color:#e2ecff;">
    <ul class="list-unstyled list-inline font-small">
      <li class="list-inline-item pr-2 white-text"><i class="fa fa-clock-o pr-1"></i><%= event.date %> , <%= event.time %></li><br>
      <!--Upvotes-->
      <li class="list-inline-item"><%= link_to like_event_path(event), method: :put do %>
      <img src="/images/upvote.png" class="w-25" style="height:15px">
      <% end %>
      </li>
      <!--Downvotes-->
      <li class="list-inline-item"><%= link_to unlike_event_path(event), method: :put do %>
      <img src="/images/downvote.png" class="w-25" style="height:15px">
      <% end %>
      </li><br>
      <li class="list-inline-item">
      Upvotes: <%= event.get_upvotes.size %>
      </li>
    </ul>
  </div>

</div>
<!-- Card -->
    </div>

      <% end %>
      <% end %>
  </div>
</div>
  



    </main>


    </main>

<!-- SCRIPTS -->
  <!-- JQuery -->
  <script type="text/javascript" src="js/jquery-3.3.1.min.js"></script>
  <!-- Bootstrap tooltips -->
  <script type="text/javascript" src="js/popper.min.js"></script>
  <!-- Bootstrap core JavaScript -->
  <script type="text/javascript" src="js/bootstrap.min.js"></script>
  <!-- MDB core JavaScript -->
  <script type="text/javascript" src="js/mdb.min.js"></script>
    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script>window.jQuery || document.write('<script src="../../assets/js/vendor/jquery-slim.min.js"><\/script>')</script>
    <script src="../../assets/js/vendor/popper.min.js"></script>
    <script src="../../dist/js/bootstrap.min.js"></script>
    <script src="../../assets/js/vendor/holder.min.js"></script>
  </body>
</html>

app/views/events/_form.html.erb
<%= form_with(model: event, local: true) do |form| %>
  <% if event.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(event.errors.count, "error") %> prohibited this event from being saved:</h2>

      <ul>
      <% event.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<div class="container" style="width:300px">
  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, class: 'form-control' %>
  </div>
  
    <div class="field">
    <%= form.label :category %>
    <%= form.text_field :category, class: 'form-control' %>
  </div>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title, class: 'form-control' %>
  </div>

 <div class="field">
    <%= form.label :date %>
    <%= form.text_field :date, class: 'form-control' %>
  </div>

 <div class="field">
    <%= form.label :time %>
    <%= form.text_field :time, class: 'form-control' %>
  </div>

  <div class="field">
    <%= form.label :details %>
    <%= form.text_field :details, class: 'form-control' %>
  </div>

  <div class="field">
    <%= form.label :location %>
    <%= form.text_field :location, class: 'form-control' %>
  </div>

  <div class="field">
    <%= form.label :imgurl %>
    <%= form.text_field :imgurl, class: 'form-control' %>
  </div>

  <div class="field">
    <%= form.label :extlink %>
    <%= form.text_field :extlink, class: 'form-control' %>
  </div>

  <div class="actions" style="text-align:center; margin-top: 50px;">
    <%= form.submit %>
  </div>
</div>
<% end %>

app/views/events/edit.html.erb
<h1>Editing Event</h1>

<%= render 'form', event: @event %>

<%= link_to 'Show', @event %> |
<%= link_to 'Back', events_path %>

app/views/events/index.html.erb
<%= render "eventshow" %>

app/views/events/new.html.erb
<h1>New Event</h1>

<%= render 'form', event: @event %>
<div style="text-align:center">
<%= link_to 'Back', events_path %>
</div>
</div>

app/views/events/show.html.erb
<head>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" 
  integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" 
  crossorigin="anonymous">
  <link href="cover.css" rel="stylesheet">
</head>

<body>
      <main role="main" class="inner cover">
   <br>     
<h3 align="center"><%= @event.date %>, <%= @event.time %></h3>
   <h1> <%= @event.name %></h1>

   <h3 align="center">at: <%= @event.location %></h3>

   



        <div class="container" style="background-color:grey;">
          <p>
          <div class="h-50 d-inline-block" align="center" style="border:1px;">
          <picture class="w-80">
            <img src="<%= @event.imgurl %>" width="75%" height="75%">
          </picture>
          </div>
        </p>
        
      </main>
    </div>
</div>
  <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
  </body>


<h4 align="center">
<p>
  <strong>Category:</strong>
  <%= @event.category.capitalize %>
</p>



<p>
  <strong>Details:</strong>
  <p>
  <%= @event.details %>
  </p>
</p>

</h4>
<h4 align="center">
<p>
  <strong>Upvotes:</strong>
  <%= @event.get_upvotes.size %>
</p>


<p>
  <a href="<%= @event.extlink %>"><strong>External Link</strong></a>
</p>

<%= link_to 'Edit', edit_event_path(@event) %> |
<%= link_to 'Back', events_path %>
</h4>

app/views/events/upvote.js.haml
:plain
    $('#upvote-count').html("#{@event.get_upvotes.size}");